### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DawoodMehmood** [DawoodMehmood/scratcher#1]
- [ ] hard code images or text written behind circles which are scratch able
- [ ] be able to scratch only a part of image and should not reveal the whole thing behind without whole thing scratched
- [ ] give scratcher a glittery look
